* ვიტრუალური გარემო virtualenv

პითონზე კოდის წერისას ხშირად არის შემთვევა, როდესაც გიწევს საცდელად რაიმე პაკეტის 
დაისტალირება და დიდი ალბათობით შემდგომში შეიძლება არც დაგჭირდეს და იყენებ მხოლოდ 
რომელიმე კონკრეტული პროექტისთვის. ზუსტად ასეთი და სხვა შემთხვევებისთვის არის
ხელსაწყო Virtual Environment. მის დახმარებით ჩვენ შგვიძლია შევქმნათ პატარა ვირტუალური
გარემო რომელიმე დირექტორიის შიგნით. მისი გააქტიურების მერე შეგვიძლია დავაინსტალიროდ 
ნებისმიერი პაკეტი რომელიც მხოლოდ ფოლდერის შიგნით იქნება მოთავსებული და არანაირ 
გავლენას არ მოახდენს სისტემაზე. virtualenv მარტივი პრაქტიკული ხელსაწყოა, 
ასე რომ ზედმეტი ახსნის გარეშე გადავიდეთ პარაქტიკულ მაგალითებზე.

** ინსტალაცია 
virtualenv-ს ვაინსტალირებთ pip პაკეტ მენეჯერით

#+BEGIN_SRC bash
pip install virtualenv
#+END_SRC

** გამოყენების მეთოდი
პირველ რიგში შევქმნათ დირექტორია ჩვენი პროექტისთვის

#+BEGIN_SRC bash
mkdir python_project
cd python_project
#+END_SRC

ვირტუალური გარემოს შექმნა 
#+BEGIN_SRC bash
virtualenv vienv
#+END_SRC
მოცემული ბრძანებით შეიქმნება დირექტორია vienv, ხოლო მის შიგნით პითონის გარემოსთვის აუცილებელი 
პროგრამები 

ასევე შეგვიძლია მიუთითოდ კონრეტურლი პითონის ინტერპრეტატორი, მაგ
#+BEGIN_SRC bash
virtualenv -p /usr/bin/python2.7 vienv
#+END_SRC

ვირტუალური გარემოს გააქტიურება vienv დირექტორიიდან, შეგვიძლია შემდეგი ბრძანებით
#+BEGIN_SRC bash
source ./bin/activate
#+END_SRC
გააქტიურების შემდეგ ვირტუალური გარემოს დასახელება vievn გამოჩნდება მარცხენა მხარეს,
ამის შემდეგ pip მენეჯერით დაინსტალირებული ნებისმიერი პაკეტი, მოთავსდება vienv ფოლდერში, 
რომელიც აბსილუტურად იზოლირებული იქნება გლობალური პითონის გარემოსგან. 

მუშაობის დასრულების შემდეგ, გარემოს დეაქტივაცია შეგვიძლია შემდეგი ბრძანებით
#+BEGIN_SRC bash
deactivate
#+END_SRC
ეს დაგვაბრუნებს გლობალურ სისტემურ გარემოში.

** დამატებითი მეთოდები და შენიშვნები
ყიველთვის როდესც ვქმნით ვირტუალურ გარემოს დამატებითი არგუმენტების გარეშე, 
ასეთ დროს ვირტუალური გარემო იქმნება აბსოლუტურად იზოლირებული. 

არის შემთხვევები როდესაც, სასურველია სისტემაში არსებული პაკეტების გამოყენება. მაგ. თუ 
გვინდა თავიდან ავიცილოთ მარავალი პაკეტის დაინსტალირების პროცესი. 
თუ ვირტუალურ გარემოს შევქმნათ --system-site-packages არგუმენტით, ასეთ დროს
დაიმპორტირდება ყველა პაკეტი რაც სისტემაში უკვე არსებობს
მაგ.
#+BEGIN_SRC bash
virtualenv vienv --system-site-packages
#+END_SRC

თუ გვინდა ვირტუალურ გარემოში დაინსტალირებული პაკეტების გამოყენება სხვა ვირტუალურ გარემოში
ან სისტემაში. ამისთვის შეგვიძლია პირტუალური გარემოდან ყველა დაინსტალირებული ფაილი შევინახოთ 
packadges.txt  ფაილში შემდეგნაირად:
#+BEGIN_SRC bash
pip freeze > packadges.txt 
#+END_SRC

ხოლო დავაინსტალიროდ სხვა გარემოში შემდეგნაირად:
#+BEGIN_SRC bash
pip install -r packadges.txt 
#+END_SRC
